//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CookingBook.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeIngridients
    {
        public int RecipeIngridientID { get; set; }
        public Nullable<int> RecipeID { get; set; }
        public Nullable<int> IngridientID { get; set; }
        public string Quantity { get; set; }
    
        public virtual Ingridients Ingridients { get; set; }
        public virtual Recipes Recipes { get; set; }
    }
}
